name: Build and publish all docker-ckan Images for minor versions
on: 
  push:
    branches:
      - master

env:
  # Build minor version images
  CKAN_2_9_MINOR: "6"
  CKAN_2_8_MINOR: "11"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ckan-base 2.8.${{ env.CKAN_2_8_MINOR }}
        uses: docker/build-push-action@v2
        with:
          context: ckan-base
          file: ckan-base/2.8/Dockerfile
          push: true
          tags: openknowledge/ckan-base:2.8.${{ env.CKAN_2_8_MINOR }}
      - name: Build ckan-base 2.9.${{ env.CKAN_2_9_MINOR }}
        uses: docker/build-push-action@v2
        with:
          context: ckan-base
          file: ckan-base/2.9/Dockerfile
          push: true
          tags: openknowledge/ckan-base:2.9.${{ env.CKAN_2_9_MINOR }}
      - name: Build ckan-base 2.9.${{ env.CKAN_2_9_MINOR }}-py2
        uses: docker/build-push-action@v2
        with:
          context: ckan-base
          file: ckan-base/2.9/Dockerfile.py2
          push: true
          tags: openknowledge/ckan-base:2.9.${{ env.CKAN_2_9_MINOR }}-py2
      - name: Build ckan-dev 2.8.${{ env.CKAN_2_8_MINOR }}
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev
          file: ckan-dev/2.8/Dockerfile
          push: true
          tags: openknowledge/ckan-dev:2.8.${{ env.CKAN_2_8_MINOR }}
      - name: Build ckan-dev 2.9.${{ env.CKAN_2_9_MINOR }}
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev
          file: ckan-dev/2.9/Dockerfile
          push: true
          tags: openknowledge/ckan-dev:2.9.${{ env.CKAN_2_9_MINOR }}
      - name: Build ckan-dev 2.9.${{ env.CKAN_2_9_MINOR }}-py2
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev
          file: ckan-dev/2.9/Dockerfile.py2
          push: true
          tags: openknowledge/ckan-dev:2.9.${{ env.CKAN_2_9_MINOR }}-py2
